### ISSUE TITLE
RFC: "Pluggable" Discover modules

### ISSUE THREAD

**Issue by reneeb** [briandfoy/cpan-audit#28]
Hi,

currently CPAN::Audit ships discover modules for cpanfiles and cpanfile.snapshots. It would be great to have some kind of plugin mechanism. That way one could write e.g. a parser for dist.ini files (Dist::Zilla)...

What do you think? Any ideas, suggestions? If you agree, I would implement something in the next week...

**Comment by briandfoy** [comment]
I'm not opposed to it, but it has to be something that doesn't take much work from me. I'm already drowning in CPAN::Audit things that need to be fixed. 

This is something where I think people need to look at how useful it is versus what else we could be doing. It you need it, then that's fine: it's useful. But if you are doing this because you think something else might need it or it makes a cleaner architecture, there might be better ways to spend time.  And, if we are going to end up in the same place after this is delivered with no additional discovery options, I wouldn't put it high on the list.

I think we'd have to rearrange quite a number of things to accommodate new options for the user, and there'd be a lot of review before we could merge it. 

That doesn't mean you shouldn't work on it, but I need to focus my CPAN::Audit time on other things for a bit. 

Other than that, yeah, let's see what that would look like.

**Comment by briandfoy** [comment]
Here are a few other things to think about.

* This is a security tool. We don't want to let the tool load stuff it isn't aware. Plugin frameworks typically trawl though their include path and load things that they discover. Search through the cpan-security-advisories and you'll see that loading untrusted code is not a rare vulnerability.
* That doesn't mean that we can't have plugins, but perhaps that we can't load them implicitly.
* CPAN::Audit should be lightweight with as few dependencies as possible. If we can parse a dist.ini statically without Dist::Zilla, that's fine. Remember that the saga of dzil started as a simple tool that exploded in complexity because of plugins. We can't bring in all of that complexity to parse a file, and the problem is that we don't know which plugin might add information that we need. I keep in mind the use case of an air gapped machine (that's why the database is pre-digested) that only has what was initially installed.

**Comment by briandfoy** [comment]
> I use a workaround at the moment (overriding the _discover_ method). So this can wait until the stuff is rearranged. If you open issues for the things that need to be fixed, I try to solve some of them.

At the moment most work is happening in briandfoy/cpan-security-advisories to clean up data. I'm focused on getting that data checked out and verified so that I can release a new version. 

#27 has me stumped and I've been ignoring it.

**Comment by briandfoy** [comment]
I think a better solution might be to let something else develop the list of modules and versions, then feed that into cpan-audit. People can then do whatever they like. That might mean a new command-line option that looks something like:

    % cpan-audit modules Foo "Bar;>=1.23" "Baz;>0,<5"

That then turns into this, where the local user decides how to make that list:

    % make_module_list | xargs cpan-audit modules
