### ISSUE TITLE
Last Update from Aug 2022? Is CPAN::Audit module dead? 

### ISSUE THREAD

**Issue by marcelser** [briandfoy/cpan-audit#32]
From what I can see at metacpan CPAN::Audit module was last updated in august 2022. As the database is a hardcoded file in this project it looks like this project is dead and --freshcheck has become quite useless? Will there be regular  updates in future or should we consider this project as abandoned? Interestingly the database in ghit github projects seems to be still updated but Audit::CPAN is not. Or should we take if from github?

**Comment by marcelser** [comment]
sorry wrong repo

**Comment by briandfoy** [comment]
It's not dead, so I'll have to look what happened with the latest release. You can tell from the issues here and in the cpan-security-advisories that work is being done.

The problem is that we dug a bit of a hole adding lots of new features and got a bit overwhelmed. There's going to be a move to have CPAN::Audit::DB be its own module but we haven't quite got there.
