### ISSUE TITLE
Feature: example drop-in cpan-audit.t file

### ISSUE THREAD

**Issue by sjn** [briandfoy/cpan-audit#40]
I think it would be great to offer a drop-in cpan-audit.t file for users to drop into their t/ directory, which does an audit and reports any security advisories on whatever is in cpanfile.snapshot, for example.

**Comment by briandfoy** [comment]
If you come up with an example, I'll include it in the distro, but, I don't think this is a good idea.

The test is indeterminate and will later fail when advisories change. A distribution that passed last month may now fail, through no fault of its own and in a way it cannot necessarily fix. This was also a problem with the old Kwalitee tests, which were not a stable target. Even as an author test, these sorts of failures are just ignored, which makes the test somewhat pointless.

Consider the case were a new CVE is reported for a module that very high in the CPAN River. A fix is not available and may not be for some time (e.g. File::Temp, a core module, has unfixed issues that are decades old). The test fails. So what do you do? Probably nothing. You'll keep using the code the way it is. So, if you aren't going to change anything, what value does the test provide? 

However, if someone wanted to do this, they should just shell out to cpan-audit if it is available, capture the JSON output, and pass or fail based on that. I think any more effort than that is probably a waste of time since almost no one is going to use a cpan-audit test.

The way forward is for someone to do this locally for awhile and figure out the idea, its downsides, and so on. After all that, if they think it is a good idea, submit a PR.

**Comment by briandfoy** [comment]
If someone wants to do this, the best way is to create Test::CPAN::Audit, either as a separate distribution or in this distribution. This would be like the Pod::Coverage / Test::Pod::Coverage divide. The Test::CPAN::Audit would have various test functions that make 

    use Test::More; 
    eval "use Test::CPAN::Audit";
    plan skip_all => "...." if $@;

    cpan_audit_ok();
    done_testing();

**Comment by sjn** [comment]
> The tests for my module are about my module, not its externalities. Other things I check with an external program, such as [Module::Release](https://metacpan.org/pod/Module::Release), which can have a more expansive or holistic view of the universe.

That's a good point. To me, though, it seems that the problem you're describing isn't related to the test itself, but rather to it's purpose and to when in a release process the test is actually run.

When I imagined this feature, I was mainly thinking of something I could drop into a t/ directory for each of the applications we have at work, so that I could get a predictable warning that the application still doesn't have any publicly known security issues in it's dependencies.

I agree completely that such a test is absolutely not useful to put in the t/ directory of CPAN modules; And I agree that something like this fits much better in the author's publishing pipeline.

(On a  side note, I also think that the split between t/ and xt/ is waaay to coarse, and that it would be meaningful to introduce some concept of "testing stages" or "testing keywords" to make it possible to only run certain tests when they offer something relevant for the situation.)

So to me, a test like this would probably have to be limited to run as part of certain test runs, as exemplified of what you can do with Toby Inkster's [Test::Modern](https://metacpan.org/pod/Test::Modern#ENVIRONMENT).

**Comment by briandfoy** [comment]
For project level stuff, I haven't used Test::More or TAP things. It would be interesting to support (as in not block) for various build/release/deploy tools to get the result of `cpan-audit` so the project can make a decision. I think we're in pretty good shape there because `cpan-audit` is careful about its exit values and what they mean.

I'm not usually working on pure-Perl projects. Often there's a huge mix of things that's not controlled by Perl's toolchain (and that's good). Calling out to any program is the same as calling out to any other program. I'd probably have a sanity check in a regular Makefile (or Ansible, whatever) the called `cpan-audit` and looked for any non-zero exit.

**Comment by briandfoy** [comment]
To wrap it up though, I'm not against this sort of thing, but I don't want to leave issues open for things that we can't work on. There are a couple of options:

* Move the idea to the wiki (which is really where things go to die) and close the issue
* We agree that we agree and close the issue. If there's something particular we want to add (say, support Ansible), open a new issue
* We figure out what concrete change we can make and do that to resolve the issue.

The best I can come up with is some documentation example in `cpan-audit` for what it already does.

**Comment by sjn** [comment]
If I get a green light to go to the PTS, I'm happy to put this on my todo-list there, so I would recommend we attempt option 3 for now. :-)

**Comment by briandfoy** [comment]
Ok, I'm going to close this issue. If you come up with something at the summit, we can open a new issue for that idea.
